export enum CartActionTypes {
  'TOGGLE_CART' = '[CART] TOOGLE_CART',
  'ADD_CART_ITEM' = '[CART] ADD_CART_ITEM',
  'REMOVE_CART_ITEM' = '[CART] REMOVE_CART_ITEM',
  'CLEAR_CART_ITEM' = '[CART] CLEAR_CART_ITEM',
  'CLEAR_CART' = '[CART] CLEAR_CART',
}
