export enum CategoryActionTypes {
  'FETCH_CATEGORIES_START' = '[CATEGORY] FETCH_CATEGORIES_START',
  'FETCH_CATEGORIES_SUCCESS' = '[CATEGORY] FETCH_CATEGORIES_SUCCESS',
  'FETCH_CATEGORIES_FAILURE' = '[CATEGORY] FETCH_CATEGORIES_FAILURE',
}
