export enum ProductsActionTypes {
  FETCH_PRODUCTS_START = '[PRODUCTS] FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS = '[PRODUCTS] FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE = '[PRODUCTS] FETCH_PRODUCTS_FAILURE',
}
